### PR TITLE
Fail-safe when target property cannot be written to (fixes #7)

### LINKED ISSUE #7: There should a fail-safe check to prevent non-writable properties from being written
I am getting this error:

```
Uncaught TypeError: Cannot assign to read only property '__reactPatchProxy' of function 'function WrappedComponent() {
            _classCallCheck(this, WrappedComponent);

            return _possibl...<omitted>... }'hoistNonReactStatics @ 
```

:cc @gajus

### PR DESCRIPTION
**Pull request by gajus**

### CODE REVIEW

**Comment by gajus** [comment]
Sorry, I am not 100% sure if that passes your linting rules because `npm run lint` is failing:

```
> hoist-non-react-statics@1.0.3 lint /Users/gajus/Documents/dev/gajus/hoist-non-react-statics
> eslint ./index.js

TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Users/gajus/Documents/dev/gajus/hoist-non-react-statics/node_modules/babel-eslint/index.js:199:40)
    at Object.exports.parse (/Users/gajus/Documents/dev/gajus/hoist-non-react-statics/node_modules/babel-eslint/index.js:410:5)
    at parse (/Users/gajus/Documents/dev/gajus/hoist-non-react-statics/node_modules/eslint/lib/eslint.js:452:27)
    at EventEmitter.module.exports.api.verify (/Users/gajus/Documents/dev/gajus/hoist-non-react-statics/node_modules/eslint/lib/eslint.js:604:15)
    at processFile (/Users/gajus/Documents/dev/gajus/hoist-non-react-statics/node_modules/eslint/lib/cli-engine.js:197:27)
    at /Users/gajus/Documents/dev/gajus/hoist-non-react-statics/node_modules/eslint/lib/cli-engine.js:332:26
    at walk (/Users/gajus/Documents/dev/gajus/hoist-non-react-statics/node_modules/eslint/lib/util/traverse.js:81:9)
    at /Users/gajus/Documents/dev/gajus/hoist-non-react-statics/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/Users/gajus/Documents/dev/gajus/hoist-non-react-statics/node_modules/eslint/lib/util/traverse.js:101:11)
```

**Comment by gajus** [comment]
Do not merge. This does not solve the issue.

**Comment by gajus** [comment]
I wondering if this should be:

```
module.exports = function hoistNonReactStatics(targetComponent, sourceComponent) {
    var sourceKeys = Object.getOwnPropertyNames(sourceComponent),
        targetKeys = Object.getOwnPropertyNames(targetComponent);
    for (var i=0; i<sourceKeys.length; ++i) {
        if (!REACT_STATICS[sourceKeys[i]] && !KNOWN_STATICS[sourceKeys[i]]) {
            try {
                targetComponent[sourceKeys[i]] = sourceComponent[sourceKeys[i]];
            } catch (error) {

            }
        }
    }

    return targetComponent;
};
```

There is no performance penalty if property is writable as expected.

**Comment by mridgway** [comment]
The visitClass error seems to be related to https://github.com/babel/babel-eslint/issues/243. Should be fixed with update to babel-eslint@4.1.7.

Are you saying that checking if the property exists already isn't helping?

File: index.js [hunk 1]
```diff
@@ -25,10 +25,11 @@ var KNOWN_STATICS = {
...
 
 module.exports = function hoistNonReactStatics(targetComponent, sourceComponent) {
-    var keys = Object.getOwnPropertyNames(sourceComponent);
-    for (var i=0; i<keys.length; ++i) {
-        if (!REACT_STATICS[keys[i]] && !KNOWN_STATICS[keys[i]]) {
-            targetComponent[keys[i]] = sourceComponent[keys[i]];
+    var sourceKeys = Object.getOwnPropertyNames(sourceComponent),
+        targetKeys = Object.getOwnPropertyNames(targetComponent);
+    for (var i=0; i<sourceKeys.length; ++i) {
+        if (!REACT_STATICS[sourceKeys[i]] && !KNOWN_STATICS[sourceKeys[i]] && targetKeys.indexOf(sourceKeys[i]) === -1) {
```
Comment (mridgway) [inline index.js]: Could we use `targetKeys.hasOwnProperty(sourceKeys[i])` here instead of `indexOf`?

Comment (gajus) [inline index.js]: No. In case of `__reactPatchProxy`, `hasOwnProperty` is returning false. I wonder if thats because of the way it is defined (https://github.com/gaearon/react-proxy/blob/v2.0.1/src/createClassProxy.js#L166-L171):

```js
Object.defineProperty(ProxyComponent, '__reactPatchProxy', {
    configurable: false,
    writable: false,
    enumerable: false,
    value: proxy
});
```

Comment (gajus) [inline index.js]: Interestingly, the very same code base (https://github.com/gaearon/react-proxy/blob/v2.0.1/src/createClassProxy.js#L33-L35) uses `Object.prototype.hasOwnProperty.call(InitialComponent, '__reactPatchProxy')` to check if property exists. Is there a reason `Object.prototype.hasOwnProperty.call` would behave different from `targetComponent.hasOwnProperty('__reactPatchProxy')`?

Comment (mridgway) [inline index.js]: Behavior shouldn't be different, but I wonder if it's inheriting that property instead of it being declared directly on the object. That code is pretty confusing, and I'm not sure which component is which.

You mentioned that the code you have here wasn't working either though and that you might need try/catch. Would it be more efficient to *just* do try/catch for now and remove the check?

Comment (gajus) [inline index.js]: > Would it be more efficient to just do try/catch for now and remove the check?

I'd say yes. `try..catch` is only an issue if it is often that the properties cannot be written to the target. Considering this is the first reported instance, that seems a rare case.

Comment (mridgway) [inline index.js]: Alright, let's do that then for now.

**Comment by gajus** [comment]
Updated PR with `tr..catch` implementation

**Comment by mridgway** [comment]
Thanks!

**Comment by gajus** [comment]
@mridgway Something is off. Look at the commit that was merged.

https://github.com/gajus/hoist-non-react-statics/commit/07ff7ff380819b0ed0ba5432706a76e257f0e8af#diff-168726dbe96b3ce427e7fedce31bb0bcR31

I apologize if I made a mistake. I don't understand how this PR picked up this commit though (and where my original commit disappeared). Even my branch is off.

Please unpublish the latest version.

Would you like me to create a new PR?

**Comment by gajus** [comment]
https://github.com/mridgway/hoist-non-react-statics/pull/10

**Comment by sunyang713** [comment]
hi, I've spent about a day tracking down this issue. So glad I found this, is this still in development?

**Comment by mridgway** [comment]
This has been released in version 1.0.5. If you're still seeing issues please open a new issue.

**Comment by sunyang713** [comment]
ah great thanks! I only install it as a co-dependency of react-css-modules, and I didn't have the update from https://github.com/gajus/react-css-modules/commit/e33ffd3a6006c7fe313f2c5b2b53a771ef52f250 just updated and got it to work!
